exclude: "docs|node_modules|migrations|.git|.tox"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.278'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
    - id: pyupgrade

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
    - id: nbqa-black
      additional_dependencies: [black==23.1.0]
    - id: nbqa-pyupgrade
      additional_dependencies: [pyupgrade==3.3.1]
    - id: nbqa-isort
      args: [--profile=black]
      additional_dependencies: [isort==5.12.0]
